### ISSUE TITLE
Move web site files into a single folder

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/DahlquistLab#1]
I am going to start using this code repository for other code besides the web site (e.g., the R normalization scripts).  Thus, I think that we should move the web site into its own directory so that we can have other top-level directories for other types of code.  We should call it something related to "web site" I guess, but I'll leave it to @NAnguiano  to decide that.

**Comment by NAnguiano** [comment]
All of the files have been moved into a folder called "site".

**Comment by kdahlquist** [comment]
confirmed
