### ISSUE TITLE
need to change file extensions from .html to .htm

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/DahlquistLab#4]
The old file extensions I used were .htm; they are now .html.  If I deploy the site with the different file extension, it will break anything that links to my site.  We need to change them, manually, if need be.

**Comment by NAnguiano** [comment]
This has been changed. All files are now in .htm format.

**Comment by kdahlquist** [comment]
OK, so I tried deploying the site again just now.  All the links were working, except that the link to the home page from the menu bar and footer just goes to myweb.lmu.edu instead of my homepage, so it gets a permission denied since it is going to the ftp root for myweb.

**Comment by NAnguiano** [comment]
quickly went ahead and made a change that I'm pretty sure will fix this. Let me know what happens.

**Comment by kdahlquist** [comment]
Confirmed that this is fixed and I have deployed the site.
